### ISSUE TITLE
lv2/lv2core/lv2.h: No such file or directory

### ISSUE THREAD

**Issue by iv-m** [x42/stereoroute.lv2#1]
I tried to build x42-plugins from http://gareus.org/misc/x42-plugins/x42-plugins-20230511.tar.xz , and encountered the following error:

```
stereoroute.c:25:10: fatal error: lv2/lv2core/lv2.h: No such file or directory
   25 | #include <lv2/lv2core/lv2.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Indeed, `lv2-devel` 1.18.10 from my distro does not have `/usr/include/lv2/lv2core/lv2.h`, only `/usr/include/lv2/core/lv2.h` is there. I haven't check yet if it's something distro-specific.

Removing extra 'lv2' helps.

```diff
@@ -22,7 +22,7 @@
 #include <math.h>

 #ifdef HAVE_LV2_1_18_6
-#include <lv2/lv2core/lv2.h>
+#include <lv2/core/lv2.h>
 #else
 #include <lv2/lv2plug.in/ns/lv2core/lv2.h>
 #endif
```

**Comment by iv-m** [comment]
There is same issue in  `x42-plugins/testsignal.lv2/testsignal.c` and `x42-plugins/matrixmixer.lv2/src/matrixmixer.c` btw.

**Comment by x42** [comment]
Thanks, fixed just now in https://gareus.org/misc/x42-plugins/x42-plugins-20230512.tar.xz

**Comment by iv-m** [comment]
> Thanks, fixed just now in https://gareus.org/misc/x42-plugins/x42-plugins-20230512.tar.xz

Thank you, works for me.
