### ISSUE TITLE
[REQ] x42-plugins repo license file

### ISSUE THREAD

**Issue by MarcoRavich** [x42/stereoroute.lv2#2]
Hi there, first of all we apologize for opening this issue (which does not concern to stereoroute itself) here but - as it is not possible to open it in the main one - it should be the "lesser evil" approach.

Since all your plugins seems to be GPL 2-licensed, can you please add a GH-compliant license file to [x42-plugins](https://github.com/x42/x42-plugins) repo too ?

This would also solve its badge generation "problem":
![](https://flat.badgen.net/github/license/x42/x42-plugins/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/x42/x42-plugins/?label=LICENSE)

Thanks in advance.

**Comment by x42** [comment]
> Since all your plugins seems to be GPL 2-licensed

While the vast majority is GPLv2+, some sources are GPLv3+, and there some ISC licensed code included as well.
While each plugin is properly licensed. There is no common license for the top-level.

Besides isn't a LICENSE file irrelevant? What matters is the license of each individual source file in the file's header.

**Comment by MarcoRavich** [comment]
Don't worry, was just a "cosmetic" request.

Thanks.
